spring:
  application:
    name: blackflag
  docker:
    compose:
      enabled: false

app:
  output-path: ${user.home}/blackflag/temp/downloads/
  zip-file-path: ${user.home}/blackflag/temp/archives/
